### ISSUE TITLE
Great runes are not supported

### ISSUE THREAD

**Issue by FanyaOff** [Shirtsy/HexPiler#3]
When I try to use the rune "Summon Great Sentiel" when trying to execute it says that there is no such rune, because the inscription of these runes depends on the seed of the world

**Comment by Shirtsy** [comment]
This is intended, as HexLator has no way to get the seed of the world or method to calculate the correct great spell patterns, only the canonical patterns are included. So to use great runes, you will need to manually specify the pattern iota. However you can define a name for the pattern to make it easier to use later, as shown in this example:
```
#def(my_summon_greater_sentinel)(@pattern(EAST,waeawaeqqqwqwqqwq))

Mind's Reflection
Compass' Purification
$my_summon_greater_sentinel
```

The definitions can be included in the same file, or you can make a separate file containing all the great spell pattern definitions for your world, and import it into your hexes with #file( [filename] ).

**Comment by FanyaOff** [comment]
how to get pattern iota? idk how to do it
